site_name: Rhine Lab
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.code.fold
    - content.tabs.link
    - header.autohide
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - palette.toggle
    - palette.switcher
    - footer.social
    - footer.icons
    - footer.navigation
    - metadata.edit
    - metadata.version
    - metadata.author
    - announcement.bar
  icon:
    repo: fontawesome/brands/github
  logo: images/logo.png